# Generated by Django 4.1.13 on 2024-07-12 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mois', models.IntegerField()),
                ('date_de_payement', models.DateField()),
                ('moyen_de_payement', models.CharField(max_length=50)),
                ('statut_de_payement', models.CharField(max_length=50)),
                ('date_debut_abonnement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AbonnementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonnement', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='BoostService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mois', models.IntegerField()),
                ('publication_affiche_fb', models.BooleanField()),
                ('comment_publication_affiche_fb', models.CharField(max_length=255)),
                ('boost_prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date_boost', models.DateField(default='')),
                ('date_fin', models.DateField()),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.abonnement')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_or_prospect', models.CharField(choices=[('Client', 'Client'), ('Prospect', 'Prospect')], max_length=50)),
                ('nom_commercial', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialites', models.CharField(max_length=255)),
                ('wilaya', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('insertion_gps', models.BooleanField()),
                ('comment_insertion_gps', models.CharField(blank=True, max_length=255, null=True)),
                ('integration_photos', models.BooleanField()),
                ('comment_integration_photos', models.CharField(blank=True, max_length=255, null=True)),
                ('remplissage_services_cabinet', models.BooleanField()),
                ('comment_remplissage_services_cabinet', models.CharField(blank=True, max_length=255, null=True)),
                ('remarque_client', models.TextField(blank=True, null=True)),
                ('agenda', models.BooleanField()),
                ('comment_agenda', models.CharField(blank=True, max_length=255, null=True)),
                ('mot_de_passe_contrat', models.BooleanField()),
                ('comment_mot_de_passe_contrat', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_recherche_premium', models.BooleanField()),
                ('comment_logo_recherche_premium', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre_logo_pub_recherche', models.IntegerField(blank=True, null=True)),
                ('mail_bienvenue', models.BooleanField()),
                ('comment_mail_bienvenue', models.CharField(blank=True, max_length=255, null=True)),
                ('appel_activation', models.BooleanField()),
                ('comment_appel_activation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('abonnement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='crm.abonnementtype')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telephone_number', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='Renouvellement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_fin_abonnement', models.DateField()),
                ('date_preavis_renouvellement', models.DateField()),
                ('mail_fin_abonnement', models.BooleanField()),
                ('comment_mail_fin_abonnement', models.CharField(blank=True, max_length=255, null=True)),
                ('viber_fin_abonnement', models.BooleanField()),
                ('comment_viber_fin_abonnement', models.CharField(blank=True, max_length=255, null=True)),
                ('appel_rdv_renouvellement', models.BooleanField()),
                ('comment_appel_rdv_renouvellement', models.CharField(blank=True, max_length=255, null=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('possibilite_renouvellement', models.IntegerField(blank=True, default=0, help_text='de 0 à 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mail_preavis_abonnement', models.BooleanField()),
                ('comment_mail_preavis_abonnement', models.CharField(blank=True, max_length=255, null=True)),
                ('date_rdv_renouvellement', models.DateField(blank=True, null=True)),
                ('resultat_rdv', models.TextField(blank=True, null=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.abonnement')),
            ],
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_pub_facebook', models.BooleanField()),
                ('comment_mail_pub_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_resultat_fb', models.BooleanField()),
                ('comment_mail_resultat_fb', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_temoignage_positive', models.BooleanField()),
                ('comment_mail_temoignage_positive', models.CharField(blank=True, max_length=255, null=True)),
                ('appel_resultat', models.BooleanField()),
                ('comment_appel_resultat', models.CharField(blank=True, max_length=255, null=True)),
                ('boost_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_service', to='crm.boostservice')),
            ],
        ),
        migrations.AddField(
            model_name='abonnement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='crm.client'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='type_abonnement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='crm.abonnementtype'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='version_offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='crm.version'),
        ),
    ]
