# Generated by Django 4.1.13 on 2024-07-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfil',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crm.client')),
                ('insertion_gps', models.BooleanField()),
                ('comment_insertion_gps', models.CharField(blank=True, max_length=255, null=True)),
                ('integration_photos', models.BooleanField()),
                ('comment_integration_photos', models.CharField(blank=True, max_length=255, null=True)),
                ('remplissage_services_cabinet', models.BooleanField()),
                ('comment_remplissage_services_cabinet', models.CharField(blank=True, max_length=255, null=True)),
                ('remarque_client', models.TextField(blank=True, null=True)),
                ('agenda', models.BooleanField()),
                ('comment_agenda', models.CharField(blank=True, max_length=255, null=True)),
                ('mot_de_passe_contrat', models.BooleanField()),
                ('comment_mot_de_passe_contrat', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_recherche_premium', models.BooleanField()),
                ('comment_logo_recherche_premium', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre_logo_pub_recherche', models.IntegerField(blank=True, null=True)),
                ('mail_bienvenue', models.BooleanField()),
                ('comment_mail_bienvenue', models.CharField(blank=True, max_length=255, null=True)),
                ('appel_activation', models.BooleanField()),
                ('comment_appel_activation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='client',
            name='appel_activation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment_agenda',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment_appel_activation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment_insertion_gps',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment_integration_photos',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment_logo_recherche_premium',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment_mail_bienvenue',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment_mot_de_passe_contrat',
        ),
        migrations.RemoveField(
            model_name='client',
            name='comment_remplissage_services_cabinet',
        ),
        migrations.RemoveField(
            model_name='client',
            name='insertion_gps',
        ),
        migrations.RemoveField(
            model_name='client',
            name='integration_photos',
        ),
        migrations.RemoveField(
            model_name='client',
            name='logo_recherche_premium',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mail_bienvenue',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mot_de_passe_contrat',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ordre_logo_pub_recherche',
        ),
        migrations.RemoveField(
            model_name='client',
            name='remarque_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='remplissage_services_cabinet',
        ),
        migrations.AlterField(
            model_name='renouvellement',
            name='abonnement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.abonnement'),
        ),
    ]
