# Generated by Django 5.0.7 on 2024-07-31 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_renouvellement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boostservice',
            name='comment_publication_affiche_fb',
        ),
    ]
