# Generated by Django 5.0.7 on 2024-08-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_clientservice_abonnement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservice',
            name='abonnement',
        ),
    ]
