# Generated by Django 5.0.7 on 2024-08-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_clientservice_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='abonnement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_services', to='crm.abonnement'),
            preserve_default=False,
        ),
    ]
