# Generated by Django 5.0.7 on 2024-08-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_clientservice_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='appel_resultat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='mail_pub_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='mail_resultat_fb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='mail_temoignage_positive',
            field=models.BooleanField(default=False),
        ),
    ]
