# Generated by Django 5.0.7 on 2024-09-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_abonnement_version_offre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du Document')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('date_upload', models.DateField(auto_now_add=True, verbose_name='Date de Téléchargement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.client', verbose_name='Client')),
            ],
        ),
    ]
